### ISSUE TITLE
Invitation didn't sent

### ISSUE THREAD

**Issue by micluka** [michael-milette/moodle-enrol_invitation#33]
Hello, I tested this plugin today and followed the instructions in the readme (https://github.com/michael-milette/moodle-enrol_invitation/blob/master/README.md).
After that, whenever I tried to send an invitation, the Moodle site showed me that it had been sent and asked whether I wanted to invite another user or not, but nothing was sent to the user I had invited, and when I checked the invitation history, it was empty??
is there any extra setting i have to do in my moodle to let this pluging work correctly?

**Comment by michael-milette** [comment]
Hi @micluka ,

Sorry to hear that you are having problems with the Invitation plugin, even on Moodle 4.2. I have not been able to reproduce your problem. Could you tell me a little more about your environment?

- Operating system
- Version of Moodle
- Version of Invitation
- Version of PHP
- Using SMTP or PHP default method
- Sending to an existing user or to an email address
- Role you are trying to assign
- Did customize any of the Invitation enrolment method settings

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
Hi again,

I just published an update on Moodle.org. It is currently the same as the version here on GitHub. Give it a try and let me know if it works any better. There are several bugs fixed in this latest release.

Best regards,

Michael

**Comment by Tanja-108** [comment]
Hello

we are facing the problem that more than 50% of the invited participants do not receive the emails. 

It seems that most of the problems occur with Gmail recipients - but also some others. 

Has anyone still the same problem? 


I am working with Mac (12.6.6)
Moodle 3.9
Invitation 2022042603


When I tried to install the newest version of INvitation (2023050700) I receive following error: 

Exception - Class 'core_user\fields' not found

What can I do?

**Comment by michael-milette** [comment]
Hi @Tanja-108 ,

I tried it on Moodle 3.9.22+ and am still unable to reproduce your issue.

Here is what you can do to help me move forward with this:

1. Login as a site administrator.
2. Navigate to Site Administration > Development > Debugging
3. Set Debug Messages to "DEVELOPER: extra Moodle debug messages for developer."
4. Make sure "Display debug messages" is checked.
5. Save your changes.

Now complete the steps to generate the exception. Be sure to document the steps and post the results here.

Once you are done, don't forget to set Debug Messages back to "NONE:..." after you are done.

If this is a production site that is always in use, and you don't want others to see error messages on your site, you can use the User Related Debugmode plugin available at https://moodle.org/plugins/tool_userdebug. What this will do for you is to just turn debugging on for specific user accounts instead of for everyone.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @micluka and @Tanja-108 ,

I just published a new release 2.2.1 of the Invitation enrolment plugin. Hope this helps.

Best regards,

Michael
